# Generated by Django 5.2.1 on 2025-06-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50, unique=True)),
                ('product_name', models.CharField(max_length=50)),
                ('product_description', models.CharField(max_length=400)),
                ('product_category', models.CharField(max_length=100)),
                ('product_img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
